server:
  port: 8082

api:
  yuzu:
    api-key: someapikey

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/stonks
    username: postgres
    password: postgre$$$
  jpa:
    generate-ddl: 'false'
    database: POSTGRESQL
    properties:
#      org.hibernate.flushMode: ALWAYS
#      hibernate.transaction.flush_before_completion: true
      hibernate.jdbc.lob.non_contextual_creation: 'true'
#      show-sql: true
#      hibernate.format_sql: true
    hibernate:
      ddl-auto: none
  devtools:
    restart:
      enabled: true

logging:
  level:
    root: INFO
    com.rno: INFO
    org.springframework: INFO
#    org.hibernate.SQL: TRACE
#    org.springframework.jdbc.core.JdbcTemplate: TRACE
#    org.springframework.jdbc.core.StatementCreatorUtils: TRACE
